[profile.default]
libs = ["dependencies"]
solc = "0.8.23"
evm_version = "paris"
[fmt]
line_length = 120
style = "tab"

[dependencies]
"@openzeppelin-contracts" = { version = "5.4.0" }

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_version = true
remappings_location = "txt"
