[compiler.solc]
target_version = "0.8.23"
evm_version = "paris"
via_IR = true
exclude_paths = ["lib", ".venv", "venv", "script", "test"]
include_paths = ["dependencies"]
remappings = ["@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.6.0-rc.1/"]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["test", "venv", ".venv"]
exclude_paths = ["lib", ".venv", "venv", "script", "test", "dependencies"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"